# -*- coding: utf-8 -*-
"""Lab 7 DS 205303  .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UZL1ymggljVrfvCzbrZUTnow7ZMEbbs
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

data = pd.read_excel("Task 1.xlsx")

months = data["Month"]
city_a_temp = data["City A Temp (Celsius)"]
city_b_temp = data["City B Temp (Celsius)"]


plt.figure(figsize=(10, 6))


plt.plot(months, city_a_temp, marker='o', label='City A', color='blue')
plt.plot(months, city_b_temp, marker='s', label='City B', color='red')


plt.xlabel("Months")
plt.ylabel("Temperature (°C)")
plt.title("Monthly Temperature Comparison between City A and City B (2024)")

plt.legend()

plt.grid(True)
plt.show()

"""**Task 1 Report**
May and June has the highest temperatures making them ideal months for hosting matches. This ensure comfortable conditions.
"""

data2 = pd.read_excel("Task 2.xlsx")

labels = data2['Month']
x = np.arange(len(labels))
width = 0.25
fig2, ax2 = plt.subplots()
ax2.grid(linestyle = '--', color = '0.75', axis = 'y')
ax2.set_axisbelow(True)
rect1 = ax2.bar(x - width/2,data2["Groceries ($) \$"], width, label = "Groceries")
rect2 = ax2.bar(x + width/2,data2["Entertainment ()"], width, label = "Entertainment")
rect3 = ax2.bar(x - width*4/2,data2["Utilities ($) \$"], width, label = "Utilities")
rect4 = ax2.bar(x + width*2/2,data2["Dining Out ()"], width, label = "Dining Out")
ax2.set_title("Monthly Expenses Breakdown by Category (Year)")
ax2.set_ylabel('Expenses')
ax2.set_xticks(x)
ax2.set_xticklabels(labels)
ax2.legend()
plt.show()

"""**Task2 Report**
Expenses are increasing because of groceries.
The month febuary has most of the expenses becuase of groceries.
The bar graph shows that **groceries** consistently have the highest expenses each month, while **entertainment** and **dining out** expenses fluctuate. Utilities remain stable throughout the year.
"""

data3 = pd.read_excel("Task 3.xlsx")

hours_of_study = data3["Hours of Study"]
exam_scores = data3["Exam Score"]

plt.figure(figsize=(8, 6))
plt.scatter(hours_of_study, exam_scores, color='blue', alpha=0.7, label='Data Points')

model = LinearRegression()
model.fit(hours_of_study.values.reshape(-1, 1), exam_scores.values.reshape(-1, 1))
plt.plot(hours_of_study, model.predict(hours_of_study.values.reshape(-1, 1)), color='red', label='Trend Line')

plt.xlabel('Hours of Study')
plt.ylabel('Exam Score')

plt.title('Relationship between Hours of Study and Exam Scores')

plt.legend()

plt.grid(True)
plt.show()

"""**Task Report 3** The scatter plot graph shows a positive correlation between study hours and exam scores. As study hours increase exam scores tend to rise.
Students who study for fewer hours (closer to the left side of the graph) generally score lower on exams.
Conversely, those who invest more time on study perform better.
While this graph doesnt prove causation, it highlights the importance of consistent study habits for attaining good grades in exams.
"""